name = "bivot"
main = "./dist/server.js"
compatibility_date="2025-09-01"

[vars]
DISCORD_APPLICATION_ID = ""
DISCORD_PUBLIC_KEY = ""
DISCORD_TOKEN = ""

[[d1_databases]]
binding = "DB"
database_name = "bivot_db"
database_id = "e07a91f2-a531-4c2a-8d7a-fa743f653140"
