services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '8080:8080'
    networks:
      - bivot-network
volumes:
  sqlite_data:
networks:
  bivot-network:
    driver: bridge
