services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - '8787:8787'
    networks:
      - bivot-network
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://app:8787
    depends_on:
      - app
    networks:
      - bivot-network
networks:
  bivot-network:
    driver: bridge
